### ISSUE TITLE
Rested Buffs are Randomly vanishing since last update

### ISSUE THREAD

**Issue by sknudskov** [Happydragun4now/DragoonCapes#14] opened 2024-02-20 03:49 UTC
We first though it was just the Adventurer cloak but now seems to be any cloak.

You get rested fine, then suddenly a few minutes later it will vanish completely or it will stay and run down like normal. Feather Cap, Leach Cape, or Adventurer cape are what we use.

**Comment by Jester2020** [comment] 2024-02-20 17:23
Yeah i've also noticed this behavior. I thought getting wet was triggering it but i'm not sure. Was happening for me with Deer and Bush capes. Haven't crafted an adventure cape yet.

**Comment by Jester2020** [comment] 2024-02-24 03:54
I've spent a couple hours testing this one. I can't find a pattern.  Sometimes i'll get the full rested counter and other times it chops 10 minutes off and 30ish seconds later chops the remainder, sometimes it's immediate and sometimes it's 3/4 the way through the rested buff.  I think it's cutting 10 minutes at a time though but i can't tell atm since i'm testing at rested 7 which is only giving 17:30.  Maybe it's doing on a timer check independant of when you  start your rested buff. Best information i can offer at this point.

**Comment by sknudskov** [comment] 2024-02-27 04:05
Tried the latest update, sadly it is still happening. Rolling back to  previous version again.

**Comment by Vitlizace** [comment] 2024-02-27 08:17
It happens when you change your armor and certain weapons. Most of the modded weapons included in this issue, and almost all armors and capes.

**Comment by sknudskov** [comment] 2024-03-02 18:26
I thappens without changing any equipment as well with any version after 1.2.81.

**Comment by RocketDrifter** [comment] 2024-03-21 05:34
Can confirm this is also happening to me, regardless of equipped cape. Specifically, it triggers every _other_ time I switch items in my hands. I also have jewelcrafting installed, if that matters. Rolling back to 1.2.2 avoids this bug.

**Comment by Happydragun4now** [comment] 2024-03-23 01:29
Fixed with 1.3.0 as per my own testing, please re-open if it still happens

**Closed by Happydragun4now** 2024-03-23 01:29 UTC

**Comment by Jester2020** [comment] 2024-03-23 11:23
Tested. Appears to be working as intended now.
