### ISSUE TITLE
Conflict with Epic Loot enchant "Feather Fall"  and wearing Linen Cape

### ISSUE THREAD

**Issue by Jester2020** [Happydragun4now/DragoonCapes#10] opened 2024-02-08 02:34 UTC
While wearing the Linen Cape with the Dragoon Cape mod enabled and EpicLoot enchants.  While i did not test for all the enchants it was apparent while wearing the cape that the enchant "Feather Fall" on another piece of gear was disabled by this. When i switch to the adventure cape feather fall worked fine. Happy to help test further.

**Comment by Happydragun4now** [comment] 2024-02-14 05:58
Hi Jester, were there any other circumstances or something specific happening to cause this? I am not able to reproduce this using a feather fall helmet (spawned in) and the linen cape, the feather fall works fine

**Comment by Jester2020** [comment] 2024-02-14 07:13
it might be due to the feather fall coming from an EpicLoot enchant vs the feather fall helmet you're mentioning. I'll attempt to repoduce it again and get back to you with the results.

**Comment by Jester2020** [comment] 2024-03-23 11:17
Linen cape no longer seems to be impacting EpicLoot Feather Fall enchant as of the current release.  I didn't exhaustively test it but while wearing the Linen cape the enchanted featherfall is working.  I think you can close this issue unless someone else has been experiencing it as of the latest release.

**Comment by Happydragun4now** [comment] 2024-03-23 21:15
Thanks Jester! Maybe this was the safeguards I added. Nobody else reported it so I'll close it for now

**Closed by Happydragun4now** 2024-03-23 21:15 UTC
